baseURL = 'https://larrythul.com/'
languageCode = 'en-us'
title = 'Larry Thul'
theme = 'PaperMod'

[params]
    env = "production"
    title = "Larry Thul"
    description = "Director of AI | PhD in Electrical Engineering | Expert in Stochastic Optimization"
    
    [params.profileMode]
        enabled = true
        title = "Larry Thul"
        subtitle = "PhD from Princeton University specializing in stochastic optimization and decision intelligence."
        imageUrl = "path/to/your/photo.jpg" # Optional
        [[params.profileMode.buttons]]
            name = "Research"
            url = "https://scholar.google.com/citations?user=IWecxBMAAAAJ"
        [[params.profileMode.buttons]]
            name = "Resume"
            url = "resume.pdf"

    [[params.socialIcons]]
        name = "linkedin"
        url = "https://www.linkedin.com/in/lawrence-thul-68b212117/"
    